# -*- coding: utf-8 -*-
"""Bookbinder.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sek3w3olmsuSzWAHKpriUOJnmh_WFEuK
"""

import pandas as pd
data=pd.read_excel("https://hogut.weebly.com/uploads/1/8/1/6/18163409/bookbinder2.xls")
#Let's see first five observation
print(data[:5])

#Describtive
print(data.describe())

data['Staus'].value_counts()

data['Choice'].value_counts()

data.groupby(['Choice','Staus']).mean()

import numpy as np
#Convert Categoric Data to 1 if Choice==Y and Choice==N 
data['Ch']=np.where(data['Choice'] =='Y', 1,0)
data.head(5)

#Split Data into Trainig and Test if Staus Trainig and TEst respectively
Training = data['Staus']=='Training'
Test = data['Staus']=='Test'
TrainingData=data[Training]
TestData=data[Test]
#Select dependent variables and independent variables for Test and Train data
X_Train=TrainingData.iloc[:,:-3]
X_Test=TestData.iloc[:,:-3]
Y_Train=TrainingData.iloc[:,-1]
Y_Test=TestData.iloc[:,-1]

import matplotlib.pyplot as plt
import pandas as pd
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score

import statsmodels.api as sm
logit_model=sm.Logit(Y_Train,X_Train)
result=logit_model.fit()
print(result.summary2())

Y_TestScore = result.predict(X_Test)
Y_Pred=np.where(Y_TestScore>0.5,1,0)
cm = metrics.confusion_matrix(Y_Pred, Y_Test)
print(cm)

